### ISSUE TITLE
Add connection diagram to electronics package product documentation

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/product-documentation#14]

**Comment by kklemens** [comment]
Connection diagrams are here: https://bluerobotics.com/learn/bluerov2-assembly/#connection-diagrams

Will need detailed diagrams/pictures/CAD models with wiring for ArduSub docs and Advanced Electronics Package.

**Comment by ghost** [comment]
Advanced ROV Electronics Assembly Guide is available[ here.](https://bluerobotics.com/learn/advanced-rov-electronics-package-assembly-guide/) Detailed wiring diagrams will be available in upcoming ArduSub docs.
