### ISSUE TITLE
Power Module: Update setup instructions

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/product-documentation#2]
The parameters should be configured on the power page, not the parameters menu. Also the parameters menu does not appear the same way in the latest software.
https://bluerobotics.com/store/comm-control-power/elec-packages/psm-asm-r2-rp/#tab-learn

**Comment by kklemens** [comment]
Fixed this on the product page and installation guide. Updated for 4.0.3 (which is what we were waiting for).
