### ISSUE TITLE
BROV2: Plug in/turn on rov should come BEFORE network setup

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/product-documentation#25]

**Comment by jaxxzer** [comment]
When network setup comes first (like it does today), users may configure the laptop's built-in network interface instead of the transient usb-ethernet interface.

**Comment by ghost** [comment]
The step for plugging in the ROV/FXTI is in the "Topside Setup" section of the Assembly guide, which then refers to the FXTI documentation. 

Should topside setup be moved to the beginning of the Software setup guide?

**Comment by ghost** [comment]
@bluerobotics/software-team a bump for my previous question:

> The step for plugging in the ROV/FXTI is in the "Topside Setup" section of the Assembly guide, which then refers to the FXTI documentation. Should topside setup be moved to the beginning of the Software setup guide?

**Comment by patrickelectric** [comment]
@danielgud Sorry for missing this, if you are waiting for any reply, you can ping the software-team or send us the link under the slack software channel.

> Should topside setup be moved to the beginning of the Software setup guide?

I believe that should stay in the assembly page, there is a reference in [the software setup page](https://bluerobotics.com/learn/bluerov2-software-setup/) for the assembly guide, where it ends with FTDI/Fathom-x connection.

Maybe after:
> These are instructions for the first time that you set up your computer to work with the BlueROV2. If you have not assembled your BlueROV2, please see our Assembly Guide and assemble your BlueROV2 prior to setting up the software.

We should add:
> Make sure to sure to have your ROV powered and with the FTDI/Fathom-x before proceeding with the instructions. 

@Williangalvani  @jaxxzer any input about this ?

**Comment by ghost** [comment]
Added this note to the software setup guide:
![image](https://user-images.githubusercontent.com/52011345/77593956-725aaa80-6eb2-11ea-8dd1-1bac4e6b738f.png)
