### ISSUE TITLE
Analog camera: Add more tech specs, pinout, input voltage range.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/product-documentation#26]
https://discuss.bluerobotics.com/t/low-light-analog-camera-question/4736

**Comment by jaxxzer** [comment]
camera specifications, output formats, lux, lens information, sensor information
https://discuss.bluerobotics.com/t/wide-angle-lens-center-of-projection/4961

**Comment by kklemens** [comment]
Analog Camera is EOL.

**Comment by rjehangir** [comment]
Closing because of EOL.
