### ISSUE TITLE
Power module R2: update BATT_VOLT_MULT location

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/product-documentation#28]
Maybe update the documentation changing the location of the 
BATT_VOLT_MULT parameter.
In the QGroundControl 3.5.0 version, It is now in the 'Advanced' 
section. https://bluerobotics.com/store/comm-control-power/elec-packages/psm-asm-r2-rp/#tab-learn

**Comment by ghost** [comment]
Updated the quick start instructions to reflect this change.
