### ISSUE TITLE
Motor Direction Configuration is Unclear

### ISSUE THREAD

**Issue by AdamBlueR** [bluerobotics/product-documentation#34]
Motor Direction configuration (https://www.bluerobotics.com/learn/bluerov2-software-setup/#configure-motor-directions):

"4. One at a time, move each slider, and make sure that the motor that spins is pushing air in the **correct direction**. If a motor is spinning in the wrong direction, click the corresponding checkbox under the 'Reverse Motor Direction' section to correct the motor rotation."

What is the correct direction? Unclear. How does slider correspond to thruster directions/air moving?

**Comment by ghost** [comment]
Changed the instructions on this step to refer to the more detailed instructions already on the QGC Motor Setup page.
