### ISSUE TITLE
lumen light missing firmware/schematic

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/product-documentation#36]
https://www.bluerobotics.com/store/thrusters/lights/lumen-r2-rp/

**Comment by ghost** [comment]
@rjehangir do we want the firmware and schematics available?

**Comment by patrickelectric** [comment]
if the firmware was made using the Arduino library, by the license we are obligated to make it public available.

**Comment by rjehangir** [comment]
@danielgud I just updated the Lumen repository to contain the most recent files. The schematic is here: https://github.com/bluerobotics/lumen/blob/master/Lumen-Schematic.pdf

**Comment by ghost** [comment]
Product page updated.
