### ISSUE TITLE
BlueROV2: Broken link at assembly instructions

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/product-documentation#38]
https://www.bluerobotics.com/learn/bluerov2-assembly/

![Screenshot from 2019-05-16 09-39-04](https://user-images.githubusercontent.com/4013804/57854471-b07d3d00-77be-11e9-93a3-0f77b2f07833.png)

**Comment by ghost** [comment]
Removed img source tag that was there by mistake.
