### ISSUE TITLE
bar100 schematic has only power supply

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/product-documentation#40]
https://bluerobotics.com/store/sensors-sonars-cameras/sensors/bar100-sensor-r1/

**Comment by rjehangir** [comment]
Here's an updated schematic.

[BAR100-SENSOR.pdf](https://github.com/bluerobotics/product-documentation/files/4162439/BAR100-SENSOR.pdf)

**Comment by ghost** [comment]
Product page has been updated with new schematic.
